// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyuemlmgvyugnublabby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5dWVtbG1ndnl1Z251YmxhYmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTM0NTQsImV4cCI6MjA2MDIyOTQ1NH0.FCXQlSf_7SoJPnX4bmUrWfYU6EkkXCZUJ8I-_YQXu1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);